# Traffic, Congestion, and Dynamic Pricing {#pricing-traffic}

#### Keywords {-}

Dynamic pricing, traffic, congestion, jam

## A beginning.
<!--Check your comments, these headings should have been changed.-->
Over the past decade the United States has seen a sustained trend of individuals moving from the periphery into urban centers.  Unfortunately, the infastructure required to accomodate these demographic shifts has not been built, and as a result traffic has increased.  And while it may be easy to forget, traffic doesn't simply cause emotional and mental anguish!  In 2013 researchers estimated the cost of congestion to be $1,700 for a car owning household (INRIX).  Given the material nature of this issue, solutions must be discovered.


## A middle.

In the absense of massive infastructure investment, states must begin to consider alternatives to reduce both the direct and indirect costs of traffic.  One solution would be to implement dynamic pricing, charging cars a variable rate to drive on a highway depending on specific factors, such as time of day, road conditions, number of passengers, etc.  If done correctly, this has the potential to significantly reduce traffic and raise money which can be used to fund additional projects.  In many ways this would represent a form of price discovery, with individuals who are willing to pay more doing so, and those who could chooes to drive at a different time having the option to save money. However if this undertaking is to be achieved, a complex model capable of predicting traffic given a variety of inputs must be created.  And this is not a new idea; academics have considered this problem and attempted to analyze different methodologies and frameworks for years.  Additionally, several states have already begun testing versions of this strategy: In Texa the TEXpress program uses variable pricing in certain highways with the aim of maintaining an average traffic speed on 50 MPH (Source), and in Virginia public-private partnerships were formed to yield new variable pricing lanes on I95 an I495.

Yet with the advent of cloud computing and newer machine learning techniques, there may be an opportunity to improve upon previous research and price modeling.  Using publically available traffic, weather, demographic, and toll data, a large scale neural network could be created which might better capture the complexity of variable interaction.  As state's begin to implement this model,  new data would feed back into the system, helping to improve the efficacy of the initial algorithim.  Because of this, the project has the potential for exponential data growth, and a robust storage and machine learning stack will be required that can easily scale.  Additionally, given the size of the data set, a parallel processing solution will be necessary;  fortunely, all of these tools are now standard in cloud solutions (AWS/Google Cloud, etc).

## An end.

Upon the completion of the model, states would have the ability to understand their expected  traffic vs. price function, and take steps to more appropriately allign reality with the state's societal and economic goals.  If implemented, the expectation would be an increase in economic activity, and a reduction in lost time.  Yet this proposal is not without flaws, primarily stemming from the potential inequity this solution might create.  Those at the bottom of the socio-economic ladder may find themselves in a position where they are unable to travel during certain times because the system is price prohibitive.  There are many potential solutions to this issue, including a cap and trade program, tax credits, and entitlement programs which would provide resources for travel to those in need, however identifying the correct approach is beyond the scope of this proposal.   In summary, we are witnessing the tragedy of the commons manifest itself in our highways system, but a data driven, dynamic pricing system can help correct preference misallignment, which in turn will yield numerous positive benefits.

## Bibliography

LBJ TEXpress Lanes Overview and Maps. (n.d.). Retrieved February 06, 2018, from http://www.lbjtexpress.com/using-lbj-texpress-lanes/lbj-texpress-lanes-overview

Project Background. (n.d.). Retrieved February 06, 2018, from https://www.expresslanes.com/project-background

INRIX. (2014, October 14). INRIX. (2014, October 14). AMERICANS WILL WASTE $2.8 TRILLION ON TRAFFIC BY 2030 IF GRIDLOCK PERSISTS [Press release]. Retrieved February 6, 2018, from AMERICANS WILL WASTE $2.8 TRILLION ON TRAFFIC BY 2030 IF GRIDLOCK PERSISTS [Press release]. Retrieved October 6, 2018, from http://inrix.com/press-releases/americans-will-waste-2-8-trillion-on-traffic-by-2030-if-gridlock-persists/

